#!/usr/bin/env zsh
if [[ -r $HOME/.displayrc ]]; then
    . $HOME/.displayrc
else
    exit 1
fi

variants=('int' 'ext' 'both')
selection=$(printf "%s\n" $variants|/usr/bin/dmenu -p display "$@")
case $selection in
    ($variants[1]) /usr/bin/xrandr --output $DISPLAY2 --off --output $DISPLAY1 --auto ;;
    ($variants[2]) /usr/bin/xrandr --output $DISPLAY1 --off --output $DISPLAY2 --auto ;;
    ($variants[3]) /usr/bin/xrandr --output $DISPLAY1 --auto --output $DISPLAY2 --auto --right-of $DISPLAY1 ;;
    (*) exit 1 ;;
esac
/usr/bin/feh --bg-scale $HOME/.wallpaper.png
/usr/bin/sleep 1
exit 0
