#!/usr/bin/env zsh
BACKGROUND='/tmp/screen_locked.png'
notify-send DUNST_COMMAND_PAUSE
scrot $BACKGROUND
mogrify -scale 10% -scale 1000% $BACKGROUND
until i3lock -entc 661111 -i $BACKGROUND; do :; done
rm $BACKGROUND
notify-send DUNST_COMMAND_RESUME
