#!/usr/bin/env bash
# cleanup -256color suffix from term and set something more compatible
typeset -A TERMS
TERMS=(
    [st]='xterm'
    [tmux]='screen'
)
TERM="${TERMS[${TERM%%-256color}]-${TERM%%-256color}}" exec ssh "$@"
