#!/usr/bin/env zsh
# run with more compatible TERM value
case $TERM in
    (st-*) ;&
    (alacritty*) ;&
    (xterm-kitty) ;&
        export TERM=xterm;;
    (rxvt-unicode-*)
        export TERM=rxvt-unicode;;
    (tmux-*)
        export TERM=screen.xterm-new;;
esac

exec "$@"
