#!/usr/bin/env bash
typeset -a vimopt=(
    '--cmd' 'let g:tvim = 1'
    '--cmd' "set tgc title titlestring=[%F]%m\\ -\\ TVIM"
    '-c' 'set mouse=a'
)

error() {
    echo "$*" >&2
    exit 1
}

termbin=$(command -v st) || termbin=$(command -v xterm) || error "No terminal found!"
vimbin=$(command -v nvim) || vimbin=$(command -v vim) || error "No vim binary found!"

exec "$termbin" -c tvim -e "$vimbin" "${vimopt[@]}" "$@" &>/dev/null & disown
