#!/usr/bin/bash
case $1 in
    -g) VIM=$(command -v gvim);;
    -n) VIM=$(command -v nvim) || VIM=$(command -v vim);;
    *) VIM=$(command -v tvim);;
esac
VIMWIKI_RC="$HOME/vimwiki/.vimwikirc"
exec flock -w0 "$VIMWIKI_RC" "$VIM" -c "source $VIMWIKI_RC"
