#!/usr/bin/env zsh

function parse_actions
{
    while read action _; do
        case $action in
            (LOCK|BLANK)
                /usr/bin/setxkbmap us -option
                /usr/bin/numlockx off
                /usr/bin/notify-send DUNST_COMMAND_PAUSE
                ;;
            (UNBLANK)
                $HOME/git/mine/vscripts/mykblayouts
                /usr/bin/notify-send DUNST_COMMAND_RESUME
                ;;
        esac
    done
}

/usr/bin/xscreensaver-command -watch | parse_actions
